name: CRD_Fusion
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.14.1
  - argcomplete=1.12.3
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - cudatoolkit=11.1.74
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.69.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - grpcio=1.38.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=7.0.4
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.7
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.3.0
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - ninja=1.10.2
  - notebook=6.4.4
  - numpy=1.21.1
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.1.3
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.10.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.7.10
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.9.0
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.1
  - scipy=1.5.2
  - send2trash=1.8.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - tensorboard=1.15.0
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.10
  - torchvision=0.10.0
  - tornado=6.1
  - traitlets=5.1.0
  - typing_extensions=3.10.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.36.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - opencv-python==3.4.4.19
    - protobuf==3.17.3
    - tensorboardx==2.4
